additive_expr = multiplicative_expr, { ("+" | "-"), multiplicative_expr } ;
multiplicative_expr = parenthetical_multiplicative_expr, { ("*" | "/"), parenthetical_multiplicative_expr } ;
parenthetical_multiplicative_expr = power_expr, { "(", additive_expr, ")" } ;
power_expr = factor, { "^", factor } ;
factor = "(", additive_expr, ")"
       | "|", additive_expr, "|"
       | function, factor
       | "-", factor
       | constant
       | number
       | identifier, [ "=", additive_expr ] ;
function = "sqrt" | "sin" | "cos" | "tan" | "log" | "abs" ;
constant = "pi" | "e" ;

identifier = "A".."z", { "A".."z" } ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
(* number = 52 or .14 or -65535 or -.256 or -340.430 etc *)
number = [ "-" ], ( digit, { digit }, [ ".", { digit } ] ) | ( ".", digit, { digit } ) ;
